### ISSUE TITLE
Generation 1 Stuff

### ISSUE THREAD

**Issue by LEGOAnimal22** [LEGOAnimal22/Pokemon_Mega_Library_C#1]
* [x] Create a header
* [x] Complete the header
* [x] Create a `.c` file with the experience functions
* [x] Create a `.c` file with the stat functions
* [x] Add the existing encounter data for Red, Blue, and Yellow (each in separate `.c` files for easy navigation)
