### ISSUE TITLE
Generation 2 Stuff

### ISSUE THREAD

**Issue by LEGOAnimal22** [LEGOAnimal22/Pokemon_Mega_Library_C#2]
* [ ] Create a header
* [ ] Complete the header
* [ ] Create a `.c` file with the experience functions
* [ ] Create a `.c` file with the stat functions
* [ ] Add the existing encounter data for Gold, Silver, and Crystal (each in separate `.c` files for easy navigation
